#!/bin/bash

# Starts a new devbox container or attaches to the running one if it exists

# Hat tip: https://gist.github.com/ekristen/11254304

function run_container {
  docker pull eremite/devbox
  docker run -it --rm --name devbox --privileged=true -v $HOME/data:/data eremite/devbox ./init.sh
}

CONTAINER=devbox

RUNNING=$(sudo docker inspect --format="{{ .State.Running }}" $CONTAINER 2> /dev/null)

if [ $? -eq 1 ]; then # doesn't exist
  run_container
elif [ "$RUNNING" == "false" ]; then
  sudo docker rm -v devbox
  run_container
else
  sudo docker attach $CONTAINER
fi
