#!/bin/bash
# Suggest a pull request
branch_name=$(git symbolic-ref -q --short HEAD)
issue_number="${branch_name%%-*}" # Keep everything to first -
issue_number=$(echo $issue_number | tr -cd [:digit:]) # Make sure issue_number is numeric
issue_summary="${branch_name#*-}" # Keep everything after first -
issue_summary="${issue_summary^}" # Capitalize first letter
issue_summary="${issue_summary//-/+}" # Replace - with +
origin=$(git config --get remote.origin.url)
regex="git@github.com:(.+).git"
[[ $origin =~ $regex ]]
repo=${BASH_REMATCH[1]}
url="https://github.com/$repo"
params="quick_pull=1&title=Deploy+to+Staging+-+${issue_summary//-/+}&body=#${issue_number}"
echo
echo "Create a pull request to staging for this branch:"
echo "${url}/compare/staging...${branch_name}?${params}"
echo
