#!/bin/bash
# Suggest a pull request
branch_name=$(git symbolic-ref -q --short HEAD)
if [ "$branch_name" == "main" -o "$branch_name" == "staging" -o "$branch_name" == "demo" ]; then
  exit
fi
if [[ $branch_name =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
  issue_number=${BASH_REMATCH[1]}
fi
pull_request_file="pr.md"
if [ -f "$pull_request_file" ]; then
  cat $pull_request_file
  echo
  issue_summary=$(head -n1 "$pull_request_file")
  issue_summary="${issue_summary// /+}" # Replace space with +
else
  issue_summary="${branch_name#*-}" # Keep everything after first -
  issue_summary="${issue_summary^}" # Capitalize first letter
  issue_summary="${issue_summary//-/+}" # Replace - with +
  issue_summary="Deploy+to+Staging:${issue_summary}"
fi
body="$issue_number"
origin=$(git config --get remote.origin.url)
url="https://github.com/${origin#*:}"
url="${url%.git}"
params="quick_pull=1&title=${issue_summary//-/+}"
echo "${url}/compare/staging...${branch_name}?${params}"
echo
