#!/bin/bash
# Append issue url to git commit message.
branch_name=$(git symbolic-ref -q --short HEAD)
if [[ $branch_name =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
  issue_number=${BASH_REMATCH[1]}
fi
first_line=$(head -n1 $1)
if [[ -z "$first_line" ]] && [[ $issue_number ]]; then
  url="https://sparefoot.atlassian.net/browse/$issue_number"
  sed -i.bak -e "1s|^|\n\nRefs: $url|" $1
fi
