# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true

Rails:
  Enabled: true

# Because I like to use braces when I pass in multiline hashes.
Style/BracesAroundHashParameters:
  Enabled: false
Style/IndentHash:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Style/Documentation:
  Enabled: false

Style/SpaceBeforeFirstArg:
  AllowForAlignment: false

Style/ExtraSpacing:
  AllowForAlignment: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines
