#!/usr/bin/env bash

if [ -d "$DATA/meta/secure" ]; then
  echo "Copying over secure credentials from meta"
  cp "$DATA/meta/secure/netrc" "$DATA/dotfiles"
  cp "$DATA/meta/secure/dockercfg" "$DATA/dotfiles"
  cp "$DATA/meta/secure/id_rsa"* "$DATA/dotfiles/ssh"
fi
