#!/bin/sh
trap 'exit' ERR
if [ -z "$PRIVATE_APP_CONFIG_DIR" ]; then
  exit
fi
app=${PWD##*/}
dir="$PRIVATE_APP_CONFIG_DIR/$app/symlinks/"
if [ -d "$dir" ]; then
  for full_path in $(find $dir -type f)
  do
    relative_path=${full_path#$dir}
    if [ -h $relative_path ]; then
      continue
    else
      if [ -f $relative_path ]; then
        rm $relative_path
      fi
    fi
    ln -s $full_path $relative_path
  done
fi
