#!/bin/sh
if [ -z "$META" ]; then
  exit
fi
app=${PWD##*/}
symlinks_path="$META/$app/symlinks"
if [ -d "$symlinks_path" ]; then
  for full_path in $(find $symlinks_path -name '*')
  do
    relative_path=${full_path#$symlinks_path/}
    if [ -h "$relative_path" -a -e "$relative_path" ]; then # if symlink (non-broken)
      continue
    elif [ -d "$full_path" -a -d "$relative_path" ]; then # existing directory
      continue
    elif [ -h $(dirname "$relative_path") ]; then # directory is already symlinked
      continue
    else
      if [ -f "$relative_path" ]; then # existing file
        rm -f $relative_path
      fi
    fi
    ln -sf $full_path $relative_path
  done
fi
